export const findIconByKeyword = (phrase) => {
    if (!phrase) return "mdi-help-circle";

    const normalizedPhrase = phrase.toLowerCase();

    for (const [icon, keywords] of Object.entries(categoryIcons)) {
        const keywordList = keywords.split(", ");
        if (keywordList.some(keyword => normalizedPhrase.includes(keyword))) {
            return icon;
        }
    }

    return "mdi-help-circle";
};

export const categoryIcons = {
    "mdi-laptop": "software, tech, app, games, communication",
    "mdi-cart": "groceries, shopping, food",
    "mdi-silverware-fork-knife": "restaurant, dining, meals",
    "mdi-coffee": "bar, cafe, coffee",
    "mdi-car": "vehicle, transportation, rideshare",
    "mdi-cash": "wage, income, salary, dues",
    "mdi-home-city": "rent, housing, mortgage",
    "mdi-filmstrip": "cinema, movies, entertainment",
    "mdi-dots-horizontal": "misc, others, filler",
    "mdi-truck-delivery": "delivery, shipping, postal",
    "mdi-home": "home, garden, maintenance",
    "mdi-gift": "gifts, donations, charity",
    "mdi-pill": "meds, pharmacy, healthcare",
    "mdi-spa": "wellness, beauty, yoga",
    "mdi-fuel": "fuel, gas, vehicle maintenance",
    "mdi-tshirt-crew": "clothes, apparel, shoes",
    "mdi-cellphone": "electronics, accessories, gadgets",
    "mdi-swap-horizontal": "transfer, transactions",
    "mdi-dog": "pets, animals, pet care",
    "mdi-help-circle": "others, missing, nonsense",
    "mdi-school": "education, development, learning",
    "mdi-clock-outline": "leisure, free time, celebrations",
    "mdi-email": "shipping, postal, communication",
    "mdi-theater": "culture, events, performances",
    "mdi-cards": "lottery, gambling, games",
    "mdi-bank": "loan, bank, mortgage, savings",
    "mdi-wrench": "maintenance, repairs, tools",
    "mdi-taxi": "taxi, rideshare, transportation",
    "mdi-human-male": "father, family, childcare",
    "mdi-currency-usd": "charges, fees, taxes, fines",
    "mdi-phone": "phone, mobile, communication",
    "mdi-cart-outline": "shopping, groceries, retail",
    "mdi-seed": "feed, agriculture, gardening",
    "mdi-water": "filler, water, hydration",
    "mdi-home-group": "housing, living, real estate",
    "mdi-wifi": "internet, connectivity",
    "mdi-controller-classic": "entertainment, gaming, leisure",
    "mdi-charity": "charity, donations, gifts",
    "mdi-hospital": "healthcare, doctor, wellness",
    "mdi-airplane": "travel, airtravel, vacation",
    "mdi-beach": "holiday, trips, relaxation",
    "mdi-party-popper": "events, celebrations, parties",
    "mdi-bus": "transportation, public transport",
    "mdi-lightning-bolt": "utilities, electricity, energy",
    "mdi-food": "food, drinks, meals",
    "mdi-diamond-stone": "jewels, luxury, accessories",
    "mdi-pot": "cooking, kitchen, recipes",
    "mdi-scooter": "scooters, rideshare, transportation",
    "mdi-run": "fitness, active sport, wellness",
    "mdi-cash-minus": "finances, expenses, budgeting",
    "mdi-puzzle": "hobbies, crafts, DIY",
    "mdi-parking": "parking, vehicle, transportation",
    "mdi-hammer-wrench": "repairs, tools, maintenance",
    "mdi-alert-circle": "fines, penalties, warnings",
    "mdi-heart-pulse": "beauty, health, fitness",
    "mdi-pencil": "stationery, tools, writing",
    "mdi-tooth": "dentist, healthcare, wellness",
    "mdi-dumbbell": "gym, fitness, exercise",
    "mdi-percent": "interests, dividends, savings",
    "mdi-arrow-up-bold": "income, revenue, earnings",
    "mdi-shield-car": "insurance, vehicle, protection",
    "mdi-tag": "sale, discounts, retail",
    "mdi-walk": "walking, leisure, exercise",
    "mdi-help-box": "missing, nonsense, unknown",
    "mdi-weather-lightning": "force, emergencies, unforeseen",
    "mdi-tools": "services, tools, repairs",
    "mdi-hand-heart": "donations, charity, kindness",
    "mdi-chart-line": "investments, finances, growth",
    "mdi-book": "books, education, learning",
    "mdi-piggy-bank": "savings, finances, budgeting",
    "mdi-wallet": "savings, finances, budgeting, wallet",
    "mdi-earth": "environment, nature, planet, global, earth",
    "mdi-library": "library, books, resources, study, education, learning, resources",
    "mdi-currency-btc": "cryptocurrency, bitcoin, blockchain, trading",
    "mdi-chart-bar": "statistics, analytics, data, insights",
    "mdi-music-note": "music, audio, sound, instruments",
    "mdi-camera": "photography, video, filming, pictures",
    "mdi-bed": "sleep, rest, relaxation, bedroom",
    "mdi-baby-carriage": "baby, childcare, kids, parenting",
    "mdi-gavel": "law, justice, court, legal",
    "mdi-sword": "weapons, medieval, combat, defense",
    "mdi-flower": "gardening, plants, nature, flora",
    "mdi-package": "packaging, parcels, delivery, shipping",
    "mdi-robot": "automation, AI, robotics, technology",
    "mdi-air-conditioner": "climate, cooling, heating, HVAC",
    "mdi-bicycle": "cycling, transport, fitness, bike",
    "mdi-calendar": "schedule, events, planner, dates",
    "mdi-printer": "printing, documents, office, paper",
    "mdi-fire": "fire, emergency, heat, safety",
    "mdi-battery": "energy, power, charge, battery",
    "mdi-weight": "weights, gym, lifting, fitness",
    "mdi-keyboard": "typing, computer, keys, input",
    "mdi-lock": "security, safety, privacy, lock",
    "mdi-umbrella": "rain, weather, protection, gear",
    "mdi-watch": "time, watches, wristwatch, style",
    "mdi-tree": "forest, nature, greenery, outdoors",
    "mdi-lighthouse": "guidance, navigation, safety, beacon",
    "mdi-campfire": "camping, outdoors, adventure, fire",
    "mdi-database": "data, storage, servers, IT",
    "mdi-basketball": "sports, basketball, fitness, games",
    "mdi-football": "sports, football, soccer, fitness",
    "mdi-volleyball": "sports, volleyball, games, beach",
    "mdi-tennis": "sports, tennis, fitness, games",
    "mdi-medal": "awards, achievement, recognition, trophies",
    "mdi-presentation": "business, presentations, meetings, slides",
    "mdi-map": "navigation, location, maps, geography",
    "mdi-compass": "navigation, direction, travel, exploration",
    "mdi-language-javascript": "programming, JavaScript, coding, development",
    "mdi-language-python": "programming, Python, coding, development",
    "mdi-language-html5": "programming, HTML, coding, development",
    "mdi-code-braces": "programming, development, coding, software",
    "mdi-drone": "drones, photography, technology, aerial",
    "mdi-shield": "security, protection, safety, defense",
    "mdi-fire-extinguisher": "safety, fire, protection, emergency",
    "mdi-parachute": "adventure, skydiving, safety, sports",
    "mdi-paw": "animals, pets, wildlife, care",
    "mdi-bug": "bugs, insects, nature, issues",
    "mdi-weather-sunny": "weather, sun, summer, outdoors",
    "mdi-weather-rainy": "weather, rain, storms, outdoors",
    "mdi-weather-snowy": "weather, snow, winter, outdoors",
    "mdi-binoculars": "exploration, searching, scouting, travel",
    "mdi-rocket": "space, exploration, travel, technology",
    "mdi-flask": "science, research, experiments, chemistry",
    "mdi-microscope": "science, biology, research, experiments",
    "mdi-thermometer": "temperature, health, climate, weather",
    "mdi-nature": "environment, eco, sustainability, greenery",
    "mdi-telescope": "astronomy, space, exploration, observation",
    "mdi-speedometer": "speed, performance, metrics, vehicles",
    "mdi-screwdriver": "tools, repair, fixing, maintenance",
    "mdi-headphones": "audio, music, sound, entertainment",
    "mdi-speaker": "audio, sound, music, devices",
    "mdi-cast": "streaming, media, devices, casting",
    "mdi-harddisk": "storage, data, backup, devices",
    "mdi-usb": "devices, storage, technology, connection",
    "mdi-cellphone-android": "phone, gadgets, technology, communication",
    "mdi-lan": "network, connection, internet, IT",
    "mdi-server": "data, server, IT, hosting",
    "mdi-camera-outline": "photos, filming, shooting, photography",
    "mdi-folder": "files, organization, data, documents",
    "mdi-cloud": "cloud, storage, internet, online",
    "mdi-fridge": "kitchen, appliances, cooling, food",
    "mdi-washing-machine": "appliances, laundry, cleaning, home",
    "mdi-door": "home, entrance, security, access",
    "mdi-lightbulb": "ideas, creativity, electricity, innovation",
    "mdi-hammer": "tools, building, repair, construction",
    "mdi-anchor": "nautical, boats, stability, security",
    "mdi-radio": "audio, news, entertainment, devices",
    "mdi-bike": "cycling, sports, transport, fitness",
    "mdi-tent": "camping, outdoors, adventure, nature",
    "mdi-bridge": "infrastructure, construction, connection, travel",
    "mdi-heart-outline": "love, care, relationships, wellness",
    "mdi-handshake": "partnership, deals, cooperation, business",
    "mdi-scale-balance": "law, justice, fairness, equality",
    "mdi-wheelchair-accessibility": "accessibility, disability, health, mobility",
    "mdi-shield-home": "safety, home, protection, security",
    "mdi-face-mask": "health, safety, protection, healthcare",
    "mdi-fruit-grapes": "food, fruit, nature, groceries",
    "mdi-beer": "drinks, beer, bar, party",
    "mdi-hamburger": "food, fast food, dining, meals",
    "mdi-tea": "drinks, tea, relaxation, beverages",
};
